//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerWebapp1.Models
{
    using CustomerWebapp1.customvalidation;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.appoinments = new HashSet<appoinment>();
            this.Vehicles = new HashSet<Vehicle>();
        }
        [Key]
        public int Id { get; set; }


        [Required(ErrorMessage = "Enter Name!")]
        [StringLength(50)]
        [Display(Name = "Name")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Enter Name!")]
        [StringLength(100)]
        [Display(Name = "Address1")]
        public string Address1 { get; set; }

        [StringLength(100)]
        [Display(Name = "Address2")]
        public string Address2 { get; set; }
        [Required(ErrorMessage = "City Name!")]
        [StringLength(50)]
        [Display(Name = "City")]
        public string City { get; set; }

        [Required(ErrorMessage = "Enter State!")]
        [StringLength(50)]

        public string State { get; set; }
        [Required(ErrorMessage = "Enter ZIP Code!")]

        public string ZipCode { get; set; }

        [Required(ErrorMessage = "Enter Email Address!")]
        [Display(Name = "Email")]
        [emailvalid]
        public string EmailId { get; set; }
        public string MobileNo { get; set; }
        public Nullable<int> DealerId { get; set; }

        [Required(ErrorMessage = "Enter Password!")]
        [Display(Name = "Password")]
        [DataType(DataType.Password)]
        [RegularExpression("([a-z]|[A-Z]|[0-9]|[\\W]){4}[a-zA-Z0-9\\W]{3,11}$", ErrorMessage = "Enter AtLest 8 Charater , one Special Symbol  and one UpperCase Letter")]

        public string Password { get; set; }

        [Required(ErrorMessage = "Enter RePassword!")]
        [Display(Name = "Re-Password")]
        [DataType(DataType.Password)]
        [Compare("Password", ErrorMessage = "Password is not identical")]

        public string Conform_Password { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<appoinment> appoinments { get; set; }
        public virtual Dealer Dealer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vehicle> Vehicles { get; set; }
    }
}
