//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerWebapp1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vehicle()
        {
            this.appoinments = new HashSet<appoinment>();
        }
    
        public string License_Plate { get; set; }
        public string Chassis_No { get; set; }
        public string OwerName { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> MechanicId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<appoinment> appoinments { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Mechanic Mechanic { get; set; }
    }
}
